# Generated by Django 3.1.3 on 2020-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
