# Generated by Django 3.1.3 on 2020-12-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_view_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogories',
            new_name='Categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='catogories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='post.Categories'),
        ),
    ]
