# Generated by Django 3.1.3 on 2020-12-20 15:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201215_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='content'),
        ),
    ]
